terra_nova_admin_profile_show:
    path:   /profil
    defaults:  { _controller: FOSUserBundle:Profile:show }
    requirements: { _method: get }

terra_nova_admin_profile_edit:
    path:   /profil/edit
    defaults:  { _controller: FOSUserBundle:Profile:edit }

terra_nova_admin_profil_change_password:
    path:   /profil/changer-de-mot-de-passe
    defaults:  { _controller: FOSUserBundle:ChangePassword:changePassword }
    requirements: { _method: get|post }

terra_nova_admin_index:
    pattern: /user
    defaults: { _controller: TerraNovaBundle:Admin:user }

terra_nova_admin_etablissement:
    pattern: /tous-les-etablissement
    defaults: { _controller: TerraNovaBundle:Admin:allEtablissement }

etablissement_admin_edit:
    pattern:  /tous-les-etablissement/{id}/edit
    defaults: { _controller: "TerraNovaBundle:Etablissement:edit" }

etablissement_admin_update:
    pattern: /tous-les-etablissement/{id}/update
    defaults: { _controller: "TerraNovaBundle:Etablissement:update" }
    requirements: { _method: post|put }