terra_nova_admin_profile_show:
    path:   /profil
    defaults:  { _controller: FOSUserBundle:Profile:show }
    requirements: { _method: get }

terra_nova_admin_profile_edit:
    path:   /profil/edit
    defaults:  { _controller: FOSUserBundle:Profile:edit }

terra_nova_admin_profil_change_password:
    path:   /profil/changer-de-mot-de-passe
    defaults:  { _controller: FOSUserBundle:ChangePassword:changePassword }
    requirements: { _method: get|post }

terra_nova_admin_index:
    pattern: /user
    defaults: { _controller: TerraNovaBundle:Admin:user }

terra_nova_add_register:
    path:   /user/add
    defaults:  { _controller: FOSUserBundle:Registration:register }

terra_nova_admin_etablissement:
    pattern: /etablissement
    defaults: { _controller: TerraNovaBundle:Admin:allEtablissement }

etablissement_admin_edit:
    pattern:  /etablissement/{id}/edit
    defaults: { _controller: "TerraNovaBundle:Etablissement:edit" }

etablissement_admin_update:
    pattern: /etablissement/{id}/update
    defaults: { _controller: "TerraNovaBundle:Etablissement:update" }
    requirements: { _method: post|put }

terra_nova_admin_etablissement_no_active:
    pattern: /etablissement/non-active
    defaults: { _controller: TerraNovaBundle:Admin:NoActiveEtablissement }

etablissement_admin_active:
    pattern: /etablissement/non-active/{id}/active
    defaults: { _controller: "TerraNovaBundle:Etablissement:active" }

etablissement_admin_new:
    pattern:  /etablissement/new
    defaults: { _controller: "TerraNovaBundle:Etablissement:new" }

etablissement_admin_create:
    pattern:  /etablissement/create
    defaults: { _controller: "TerraNovaBundle:Etablissement:create" }
    requirements: { _method: post }

etablissement_admin_delete:
    pattern:  /etablissement/{id}/delete
    defaults: { _controller: "TerraNovaBundle:Etablissement:delete" }
    requirements: { _method: post|delete }

TerraNovaBundle_theme:
    resource: "@TerraNovaBundle/Resources/config/routing/theme.yml"
    prefix:   /theme

TerraNovaBundle_soustheme:
    resource: "@TerraNovaBundle/Resources/config/routing/soustheme.yml"
    prefix:   /soustheme

TerraNovaBundle_reward:
    resource: "@TerraNovaBundle/Resources/config/routing/reward.yml"
    prefix:   /reward

TerraNovaBundle_badge:
    resource: "@TerraNovaBundle/Resources/config/routing/badge.yml"
    prefix:   /badge


TerraNovaBundle_trophy:
    resource: "@TerraNovaBundle/Resources/config/routing/trophy.yml"
    prefix:   /trophy