terra_nova_enseigant_index:
    pattern:   /
    defaults:  { _controller: TerraNovaBundle:Enseignant:index }

terra_nova_enseigant_connection:
    path:	/connexion
    defaults:  { _controller: FOSUserBundle:Security:login }

terra_nova_enseigant_register:
    path:      /inscription
    defaults:  { _controller: FOSUserBundle:Registration:register }

terra_nova_enseigant_profile_show:
    path:	/profil
    defaults:  { _controller: FOSUserBundle:Profile:show }
    requirements: { _method: get }

terra_nova_enseigant_profile_edit:
    path:	/profil/edit
    defaults:  { _controller: FOSUserBundle:Profile:edit }