terra_nova_enseigant_index:
    pattern:   /
    defaults:  { _controller: TerraNovaBundle:Enseignant:index }

terra_nova_enseignant_profile_show:
    path:   /profil
    defaults:  { _controller: FOSUserBundle:Profile:show }
    requirements: { _method: get }

terra_nova_enseignant_profile_edit:
    path:   /profil/edit
    defaults:  { _controller: FOSUserBundle:Profile:edit }

terra_nova_enseignant_profil_change_password:
    path:   /profil/changer-de-mot-de-passe
    defaults:  { _controller: FOSUserBundle:ChangePassword:changePassword }
    requirements: { _method: get|post }

TerraNovaBundle_etablissement:
    resource: "@TerraNovaBundle/Resources/config/routing/etablissement.yml"
    prefix:   /etablissement

TerraNovaBundle_classe:
    resource: "@TerraNovaBundle/Resources/config/routing/classe.yml"
    prefix:   /classe

TerraNovaBundle_seance:
    resource: "@TerraNovaBundle/Resources/config/routing/seance.yml"
    prefix:   /seance