terra_nova_homepage:
    pattern:  /
    defaults: { _controller: TerraNovaBundle:Default:index }

terra_nova_enseigant_connection:
    path:   /connexion
    defaults:  { _controller: FOSUserBundle:Security:login }

terra_nova_enseignant:
    resource: "@TerraNovaBundle/Resources/config/routing/enseignant.yml"
    prefix: /enseignant

terra_nova_admin:
    resource: "@TerraNovaBundle/Resources/config/routing/admin.yml"
    prefix: /admin

terra_nova_api:
    resource: "@TerraNovaBundle/Resources/config/routing/api.yml"
    type:   rest
