terra_nova_homepage:
    pattern:  /
    defaults: { _controller: TerraNovaBundle:Default:index }

terra_nova_enseignant:
    resource: "@TerraNovaBundle/Resources/config/routing/enseignant.yml"
    prefix: /enseignant

terra_nova_api:
    resource: "@TerraNovaBundle/Resources/config/routing/api.yml"
    type:   rest