parameters:
#    terra_nova.example.class: Terra\NovaBundle\Example

services:
    terra_nova.registration.form.type:
        class: Terra\NovaBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: terra_nova_registration }
#    terra_nova.example:
#        class: %terra_nova.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
