security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_ENSEIGNANT: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: /enseignant/connexion
                provider: fos_userbundle
                remember_me: true
                csrf_provider: form.csrf_provider
                check_path: /enseignant/login_check
                default_target_path: /enseignant
            logout:
                path:   /enseignant/logout
            anonymous:    true

    access_control:
        - { path: ^/enseignant/connexion$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/enseignant/inscription$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/enseignant/inscription/confirmation, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/enseignant/inscription/envoi-email-de-confirmation-d-inscription$, role:IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/enseignant, role: ROLE_ADMIN_ENSEIGANT }
        # IS_AUTHENTICATED_FULLY
