<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140429121832 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE ResultSubTheme (id INT AUTO_INCREMENT NOT NULL, seance_id INT DEFAULT NULL, student_id INT DEFAULT NULL, cozeText VARCHAR(255) NOT NULL, dragCozeText VARCHAR(255) NOT NULL, trueFalse VARCHAR(255) NOT NULL, freeSentence VARCHAR(255) NOT NULL, success INT NOT NULL, timePassing TIME NOT NULL, levelSuccess VARCHAR(255) NOT NULL, sousTheme_id INT DEFAULT NULL, INDEX IDX_E645EC1E3797A94 (seance_id), INDEX IDX_E645EC1CB944F1A (student_id), INDEX IDX_E645EC1F7358FE1 (sousTheme_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE ResultSubTheme ADD CONSTRAINT FK_E645EC1E3797A94 FOREIGN KEY (seance_id) REFERENCES Seance (id)");
        $this->addSql("ALTER TABLE ResultSubTheme ADD CONSTRAINT FK_E645EC1CB944F1A FOREIGN KEY (student_id) REFERENCES Student (id)");
        $this->addSql("ALTER TABLE ResultSubTheme ADD CONSTRAINT FK_E645EC1F7358FE1 FOREIGN KEY (sousTheme_id) REFERENCES SousTheme (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE ResultSubTheme");
    }
}
