<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140424101157 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE User ADD currentClass_id INT DEFAULT NULL, DROP current_class");
        $this->addSql("ALTER TABLE User ADD CONSTRAINT FK_2DA17977CD330DBE FOREIGN KEY (currentClass_id) REFERENCES Classe (id)");
        $this->addSql("CREATE INDEX IDX_2DA17977CD330DBE ON User (currentClass_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE User DROP FOREIGN KEY FK_2DA17977CD330DBE");
        $this->addSql("DROP INDEX IDX_2DA17977CD330DBE ON User");
        $this->addSql("ALTER TABLE User ADD current_class INT NOT NULL, DROP currentClass_id");
    }
}
