<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140410144919 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Trophy ADD path VARCHAR(255) NOT NULL, ADD sousTheme_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Trophy ADD CONSTRAINT FK_1686FFDFF7358FE1 FOREIGN KEY (sousTheme_id) REFERENCES SousTheme (id)");
        $this->addSql("CREATE INDEX IDX_1686FFDFF7358FE1 ON Trophy (sousTheme_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Trophy DROP FOREIGN KEY FK_1686FFDFF7358FE1");
        $this->addSql("DROP INDEX IDX_1686FFDFF7358FE1 ON Trophy");
        $this->addSql("ALTER TABLE Trophy DROP path, DROP sousTheme_id");
    }
}
