<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140514235417 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("CREATE SEQUENCE Badge_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Classe_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Etablissement_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE ResultStudent_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE ResultSubTheme_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Reward_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Seance_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE SousTheme_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Student_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Theme_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE Trophy_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE SEQUENCE fos_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
        $this->addSql("CREATE TABLE Badge (id INT NOT NULL, reward_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_3F316719E466ACA1 ON Badge (reward_id)");
        $this->addSql("CREATE TABLE Classe (id INT NOT NULL, etablissement_id INT DEFAULT NULL, enseignant_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, niveau VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_882BBAA0FF631228 ON Classe (etablissement_id)");
        $this->addSql("CREATE INDEX IDX_882BBAA0E455FCC0 ON Classe (enseignant_id)");
        $this->addSql("CREATE TABLE Etablissement (id INT NOT NULL, numero_national INT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, code_postal INT NOT NULL, ville VARCHAR(255) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE ResultStudent (id INT NOT NULL, student_id INT DEFAULT NULL, success INT NOT NULL, timePassing TIME(0) WITHOUT TIME ZONE NOT NULL, NbThemePlay INT NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_D64C0185CB944F1A ON ResultStudent (student_id)");
        $this->addSql("CREATE TABLE ResultSubTheme (id INT NOT NULL, seance_id INT DEFAULT NULL, student_id INT DEFAULT NULL, cozeText VARCHAR(255) NOT NULL, dragCozeText VARCHAR(255) NOT NULL, trueFalse VARCHAR(255) NOT NULL, freeSentence VARCHAR(255) NOT NULL, success INT NOT NULL, raTime TIME(0) WITHOUT TIME ZONE NOT NULL, gameTime TIME(0) WITHOUT TIME ZONE NOT NULL, timePassing TIME(0) WITHOUT TIME ZONE NOT NULL, levelSuccess VARCHAR(255) NOT NULL, sousTheme_id INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_E645EC1E3797A94 ON ResultSubTheme (seance_id)");
        $this->addSql("CREATE INDEX IDX_E645EC1CB944F1A ON ResultSubTheme (student_id)");
        $this->addSql("CREATE INDEX IDX_E645EC1F7358FE1 ON ResultSubTheme (sousTheme_id)");
        $this->addSql("CREATE TABLE Reward (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE Seance (id INT NOT NULL, classe_id INT DEFAULT NULL, theme_id INT DEFAULT NULL, enseignant_id INT DEFAULT NULL, date DATE NOT NULL, heure TIME(0) WITHOUT TIME ZONE NOT NULL, intro VARCHAR(255) NOT NULL, test BOOLEAN NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_D8D1F8388F5EA509 ON Seance (classe_id)");
        $this->addSql("CREATE INDEX IDX_D8D1F83859027487 ON Seance (theme_id)");
        $this->addSql("CREATE INDEX IDX_D8D1F838E455FCC0 ON Seance (enseignant_id)");
        $this->addSql("CREATE TABLE SousTheme (id INT NOT NULL, theme_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_76D64F859027487 ON SousTheme (theme_id)");
        $this->addSql("CREATE TABLE Student (id INT NOT NULL, classe_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, login VARCHAR(255) NOT NULL, firstName VARCHAR(255) NOT NULL, age INT NOT NULL, avatar INT NOT NULL, remarks VARCHAR(4096) DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_789E96AF8F5EA509 ON Student (classe_id)");
        $this->addSql("CREATE TABLE Theme (id INT NOT NULL, name VARCHAR(255) NOT NULL, age_min INT NOT NULL, age_max INT NOT NULL, path VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE TABLE Trophy (id INT NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, path VARCHAR(255) NOT NULL, sousTheme_id INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE INDEX IDX_1686FFDFF7358FE1 ON Trophy (sousTheme_id)");
        $this->addSql("CREATE TABLE fos_user (id INT NOT NULL, etablissement_id INT DEFAULT NULL, username VARCHAR(255) NOT NULL, username_canonical VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, email_canonical VARCHAR(255) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, locked BOOLEAN NOT NULL, expired BOOLEAN NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles TEXT NOT NULL, credentials_expired BOOLEAN NOT NULL, credentials_expire_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, name VARCHAR(100) DEFAULT NULL, currentClass_id INT DEFAULT NULL, PRIMARY KEY(id))");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_957A647992FC23A8 ON fos_user (username_canonical)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_957A6479A0D96FBF ON fos_user (email_canonical)");
        $this->addSql("CREATE INDEX IDX_957A6479CD330DBE ON fos_user (currentClass_id)");
        $this->addSql("CREATE INDEX IDX_957A6479FF631228 ON fos_user (etablissement_id)");
        $this->addSql("COMMENT ON COLUMN fos_user.roles IS '(DC2Type:array)'");
        $this->addSql("ALTER TABLE Badge ADD CONSTRAINT FK_3F316719E466ACA1 FOREIGN KEY (reward_id) REFERENCES Reward (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Classe ADD CONSTRAINT FK_882BBAA0FF631228 FOREIGN KEY (etablissement_id) REFERENCES Etablissement (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Classe ADD CONSTRAINT FK_882BBAA0E455FCC0 FOREIGN KEY (enseignant_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE ResultStudent ADD CONSTRAINT FK_D64C0185CB944F1A FOREIGN KEY (student_id) REFERENCES Student (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE ResultSubTheme ADD CONSTRAINT FK_E645EC1E3797A94 FOREIGN KEY (seance_id) REFERENCES Seance (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE ResultSubTheme ADD CONSTRAINT FK_E645EC1CB944F1A FOREIGN KEY (student_id) REFERENCES Student (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE ResultSubTheme ADD CONSTRAINT FK_E645EC1F7358FE1 FOREIGN KEY (sousTheme_id) REFERENCES SousTheme (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Seance ADD CONSTRAINT FK_D8D1F8388F5EA509 FOREIGN KEY (classe_id) REFERENCES Classe (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Seance ADD CONSTRAINT FK_D8D1F83859027487 FOREIGN KEY (theme_id) REFERENCES Theme (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Seance ADD CONSTRAINT FK_D8D1F838E455FCC0 FOREIGN KEY (enseignant_id) REFERENCES fos_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE SousTheme ADD CONSTRAINT FK_76D64F859027487 FOREIGN KEY (theme_id) REFERENCES Theme (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Student ADD CONSTRAINT FK_789E96AF8F5EA509 FOREIGN KEY (classe_id) REFERENCES Classe (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE Trophy ADD CONSTRAINT FK_1686FFDFF7358FE1 FOREIGN KEY (sousTheme_id) REFERENCES SousTheme (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE fos_user ADD CONSTRAINT FK_957A6479CD330DBE FOREIGN KEY (currentClass_id) REFERENCES Classe (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE fos_user ADD CONSTRAINT FK_957A6479FF631228 FOREIGN KEY (etablissement_id) REFERENCES Etablissement (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE Seance DROP CONSTRAINT FK_D8D1F8388F5EA509");
        $this->addSql("ALTER TABLE Student DROP CONSTRAINT FK_789E96AF8F5EA509");
        $this->addSql("ALTER TABLE fos_user DROP CONSTRAINT FK_957A6479CD330DBE");
        $this->addSql("ALTER TABLE Classe DROP CONSTRAINT FK_882BBAA0FF631228");
        $this->addSql("ALTER TABLE fos_user DROP CONSTRAINT FK_957A6479FF631228");
        $this->addSql("ALTER TABLE Badge DROP CONSTRAINT FK_3F316719E466ACA1");
        $this->addSql("ALTER TABLE ResultSubTheme DROP CONSTRAINT FK_E645EC1E3797A94");
        $this->addSql("ALTER TABLE ResultSubTheme DROP CONSTRAINT FK_E645EC1F7358FE1");
        $this->addSql("ALTER TABLE Trophy DROP CONSTRAINT FK_1686FFDFF7358FE1");
        $this->addSql("ALTER TABLE ResultStudent DROP CONSTRAINT FK_D64C0185CB944F1A");
        $this->addSql("ALTER TABLE ResultSubTheme DROP CONSTRAINT FK_E645EC1CB944F1A");
        $this->addSql("ALTER TABLE Seance DROP CONSTRAINT FK_D8D1F83859027487");
        $this->addSql("ALTER TABLE SousTheme DROP CONSTRAINT FK_76D64F859027487");
        $this->addSql("ALTER TABLE Classe DROP CONSTRAINT FK_882BBAA0E455FCC0");
        $this->addSql("ALTER TABLE Seance DROP CONSTRAINT FK_D8D1F838E455FCC0");
        $this->addSql("DROP SEQUENCE Badge_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Classe_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Etablissement_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE ResultStudent_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE ResultSubTheme_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Reward_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Seance_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE SousTheme_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Student_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Theme_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE Trophy_id_seq CASCADE");
        $this->addSql("DROP SEQUENCE fos_user_id_seq CASCADE");
        $this->addSql("DROP TABLE Badge");
        $this->addSql("DROP TABLE Classe");
        $this->addSql("DROP TABLE Etablissement");
        $this->addSql("DROP TABLE ResultStudent");
        $this->addSql("DROP TABLE ResultSubTheme");
        $this->addSql("DROP TABLE Reward");
        $this->addSql("DROP TABLE Seance");
        $this->addSql("DROP TABLE SousTheme");
        $this->addSql("DROP TABLE Student");
        $this->addSql("DROP TABLE Theme");
        $this->addSql("DROP TABLE Trophy");
        $this->addSql("DROP TABLE fos_user");
    }
}
